version: '3.8'

networks:
  mailnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  james:
    image: apache/james:latest
    container_name: james
    hostname: james.local
    ports:
      - "25:25"    # SMTP
      - "110:110"  # POP3
      - "143:143"  # IMAP
      - "465:465"  # SMTPS
      - "587:587"  # Submission
      - "993:993"  # IMAPS
      - "8000:8000" # WebAdmin
    volumes:
      - ./james/conf:/root/conf
      - ./james/log4j2.xml:/opt/james/conf/log4j2.xml
      - ./james/home:/home
      - ./james_logs:/opt/james/logs
    networks:
      mailnet:
        ipv4_address: 172.20.0.2

  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./fail2ban/:/config/fail2ban/
      - ./fail2ban/opt/log4j2.xml:/opt/james/conf/log4j2.xml
      - ./james_logs:/opt/james/logs
    networks:
      mailnet:
        ipv4_address: 172.20.0.3
    depends_on:
      - james

  legit-client: 
    image: debian:latest
    container_name: client2
    volumes:
      - ./client:/home
    stdin_open: true
    tty: true
    networks:
      mailnet:
        ipv4_address: 172.20.0.4

  attacker:
    image: debian:latest
    container_name: attacker2
    volumes:
      - ./attacker:/home
    stdin_open: true
    tty: true
    networks:
      mailnet:
        ipv4_address: 172.20.0.5

volumes:
  james_logs:

